version: "2"
#
# Services
#
services:
  calculation-service:
      build: ./service
      volumes:
        - ./docker/calculation-service/config:/config
        - ./ui/dgp-calculators-playground:/public
      ports:
        - 8090:8090
      networks:
          - localnet



# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true