
# Singleton service factory configuration/IoC injection
singletons:
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
# - com.networknt.server.StartupHookProvider:
  # - com.networknt.server.Test1StartupHook
  # - com.networknt.server.Test2StartupHook
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
# - com.networknt.server.ShutdownHookProvider:
  # - com.networknt.server.Test1ShutdownHook

- io.beanmapper.BeanMapper: com.capco.utils.DependencyInjector::beanMapper
- com.capco.dgp.calculator.core.Calculator: com.capco.utils.DependencyInjector::goalsCalculator
- com.capco.calculator.validator.CalcActionGoalsValidator:
  - com.capco.calculator.validator.CalcActionGoalsValidator
- com.capco.calculator.validator.MoneyActionGoalsValidator:
  - com.capco.calculator.validator.MoneyActionGoalsValidator